const products = [
  {
    id: 1,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (9).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 2,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (1).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 3,
    name: "Nike Air Force 2",
    price: 115,
    image: "src/assets/Puma (2).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 4,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (3).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 5,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (4).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 6,
    name: "Jordans Superstar",
    price: 100,
    image: "src/assets/Puma (5).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 7,
    name: "Sneakers",
    price: 115,
    image: "src/assets/Puma (8).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 8,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (7).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 9,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (8).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },

  // PG2
  {
    id: 1,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (9).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 2,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (1).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 3,
    name: "Nike Air Force 2",
    price: 115,
    image: "src/assets/Puma (2).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 4,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (3).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 5,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (4).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 6,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (5).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 7,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (8).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 8,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (7).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 9,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (8).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },

  //PG3
  {
    id: 1,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (9).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 2,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (1).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 3,
    name: "Nike Air Force 2",
    price: 115,
    image: "src/assets/Puma (2).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 4,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (3).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 5,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (4).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 6,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (5).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 7,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (8).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 8,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (7).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 9,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (8).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 1,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (9).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 2,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (1).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 3,
    name: "Nike Air Force 2",
    price: 115,
    image: "src/assets/Puma (2).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 4,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (3).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 5,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (4).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 6,
    name: "Jordans Superstar",
    price: 100,
    image: "src/assets/Puma (5).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 7,
    name: "Sneakers",
    price: 115,
    image: "src/assets/Puma (8).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 8,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (7).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 9,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (8).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },

  // PG2
  {
    id: 1,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (9).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 2,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (1).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 3,
    name: "Nike Air Force 2",
    price: 115,
    image: "src/assets/Puma (2).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 4,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (3).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 5,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (4).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 6,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (5).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 7,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (8).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 8,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (7).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 9,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (8).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },

  //PG3
  {
    id: 1,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (9).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 2,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (1).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 3,
    name: "Nike Air Force 2",
    price: 115,
    image: "src/assets/Puma (2).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 4,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (3).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 5,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (4).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 6,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (5).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 7,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (8).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
  {
    id: 8,
    name: "Adidas Superstar",
    price: 100,
    image: "src/assets/Puma (7).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "9",
  },
  {
    id: 9,
    name: "Nike Air Force 1",
    price: 115,
    image: "src/assets/Puma (8).jpeg",
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc ",
    size: "10",
  },
];

export default products;
