import Puma1 from '../assets/Puma (1).jpeg';
import Puma2 from '../assets/Puma (2).jpeg';
import Puma3 from '../assets/Puma (3).jpeg';
import Puma4 from '../assets/Puma (4).jpeg';
import Puma5 from '../assets/Puma (5).jpeg';
import Puma7 from '../assets/Puma (7).jpeg';
import Puma8 from '../assets/Puma (8).jpeg';
import Puma9 from '../assets/Puma (9).jpeg';
import Shirt1 from '../assets/Shirt(1).jpeg';
import Shirt2 from '../assets/Shirt(2).jpeg';
import Shirt3 from '../assets/Shirt(3).jpeg';
import Shirt4 from '../assets/Shirt(4).jpeg';
import Hoodie1 from '../assets/Hoodie(1).jpeg';
import Hoodie2 from '../assets/Hoodie(2).jpeg';
import Hoodie3 from '../assets/Hoodie(3).jpeg';
import Sweater2 from '../assets/Sweater(2).jpeg';

const Products = [
  // Sneakers Collection
  {
    id: 101,
    name: "White Sneakers",
    price: 115,
    image: Puma9,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "10",
  },
  {
    id: 102,
    name: "Black Sneakers",
    price: 100,
    image: Puma1,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "9",
  },
  {
    id: 103,
    name: "Nike Sneakers",
    price: 115,
    image: Puma2,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "10",
  },
  {
    id: 104,
    name: "Adidas Sneakers",
    price: 100,
    image: Puma3,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "9",
  },
  {
    id: 105,
    name: "Running Shoes",
    price: 115,
    image: Puma4,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "10",
  },
  {
    id: 106,
    name: "Jordans",
    price: 100,
    image: Puma5,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "9",
  },
  {
    id: 107,
    name: "Casual Sneakers",
    price: 115,
    image: Puma8,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "10",
  },
  {
    id: 108,
    name: "Sport Sneakers",
    price: 100,
    image: Puma7,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "9",
  },

  // Duplicate sneakers (kept as requested)
  {
    id: 101,
    name: "White Sneakers",
    price: 115,
    image: Puma9,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "10",
  },
  {
    id: 102,
    name: "Black Sneakers",
    price: 100,
    image: Puma1,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "9",
  },
  {
    id: 103,
    name: "Nike Sneakers",
    price: 115,
    image: Puma2,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "10",
  },
  {
    id: 104,
    name: "Adidas Sneakers",
    price: 100,
    image: Puma3,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "9",
  },
  {
    id: 105,
    name: "Running Shoes",
    price: 115,
    image: Puma4,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "10",
  },
  {
    id: 106,
    name: "Jordans",
    price: 100,
    image: Puma5,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "9",
  },
  {
    id: 107,
    name: "Casual Sneakers",
    price: 115,
    image: Puma8,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "10",
  },
  {
    id: 108,
    name: "Sport Sneakers",
    price: 100,
    image: Puma7,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "9",
  },

  // Shirts Collection
  {
    id: 201,
    name: "Blue Shirt",
    price: 40,
    image: Shirt1,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "10",
  },
  {
    id: 202,
    name: "White Shirt",
    price: 100,
    image: Shirt3,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "9",
  },
  {
    id: 203,
    name: "Checkered Shirt",
    price: 50,
    image: Shirt2,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "10",
  },
  {
    id: 204,
    name: "Black Shirt",
    price: 40,
    image: Shirt4,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "9",
  },

  // Duplicate shirts
  {
    id: 201,
    name: "Blue Shirt",
    price: 40,
    image: Shirt1,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "10",
  },
  {
    id: 202,
    name: "White Shirt",
    price: 100,
    image: Shirt3,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "9",
  },
  {
    id: 203,
    name: "Checkered Shirt",
    price: 50,
    image: Shirt2,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "10",
  },
  {
    id: 204,
    name: "Black Shirt",
    price: 40,
    image: Shirt4,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "9",
  },

  // Hoodies & Sweaters
  {
    id: 301,
    name: "Black Hoodie",
    price: 60,
    image: Hoodie1,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "10",
  },
  {
    id: 302,
    name: "Grey Hoodie",
    price: 90,
    image: Hoodie2,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "9",
  },
  {
    id: 303,
    name: "Zip Hoodie",
    price: 65,
    image: Hoodie3,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "10",
  },
  {
    id: 304,
    name: "Beige Sweater",
    price: 70,
    image: Sweater2,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "9",
  },

  // Duplicate hoodies
  {
    id: 301,
    name: "Black Hoodie",
    price: 60,
    image: Hoodie1,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "10",
  },
  {
    id: 302,
    name: "Grey Hoodie",
    price: 90,
    image: Hoodie2,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "9",
  },
  {
    id: 303,
    name: "Zip Hoodie",
    price: 65,
    image: Hoodie3,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "10",
  },
  {
    id: 304,
    name: "Beige Sweater",
    price: 70,
    image: Sweater2,
    color1: "darkorchid",
    color2: "grey",
    color3: "#ccc",
    size: "9",
  }
];

export default Products;